### ISSUE TITLE
Support bucket authentification

### ISSUE THREAD

**Issue by blackrez** [criteo/mewpoke#30] opened 2018-02-15 16:31 UTC
Hello,

Is it possible to add bucket authentification ?

Thanks

**Comment by mcoolive** [comment] 2018-02-26 10:55
Should be fixed by [9019467](https://github.com/criteo/mewpoke/commit/9019467a21453c6dbabbdb98d031caad84997043).

**Comment by mcoolive** [comment] 2018-03-02 16:32
Can you test our fix?

**Comment by blackrez** [comment] 2018-03-06 13:50
Thank you, authentification works but there's no metrics.

```
[globalEventExecutor-2-4] INFO com.couchbase.client.core.env.CoreEnvironment - Shutdown IoPool: success 
[Thread-13] INFO com.couchbase.client.core.env.CoreEnvironment - Shutdown Netty: failure 
[Thread-13] INFO com.couchbase.client.core.env.CoreEnvironment - Netty shutdown is best effort, ignoring failure
[main] INFO com.criteo.nosql.mewpoke.couchbase.CouchbaseRunnerAbstract - UPDATE_TOPOLOGY took 3101 ms
[main] INFO com.criteo.nosql.mewpoke.couchbase.CouchbaseRunnerAbstract - WAIT took 70 ms
[main] ERROR com.criteo.nosql.mewpoke.couchbase.CouchbaseMonitor - uri /pools/default/buckets/alert/nodes/10.9.124.126:8091/stats does not return 200
[main] ERROR com.criteo.nosql.mewpoke.couchbase.CouchbaseMonitor - uri /pools/default/buckets/data/nodes/10.9.124.126:8091/stats does not return 200
[main] INFO com.criteo.nosql.mewpoke.couchbase.CouchbaseRunnerAbstract - POKE took 144 ms
[main] INFO com.criteo.nosql.mewpoke.couchbase.CouchbaseRunnerAbstract - WAIT took 29855 ms
[main] ERROR com.criteo.nosql.mewpoke.couchbase.CouchbaseMonitor - uri /pools/default/buckets/alert/nodes/10.9.124.126:8091/stats does not return 200
[main] ERROR com.criteo.nosql.mewpoke.couchbase.CouchbaseMonitor - uri /pools/default/buckets/data/nodes/10.9.124.126:8091/stats does not return 200
[main] INFO com.criteo.nosql.mewpoke.couchbase.CouchbaseRunnerAbstract - POKE took 175 ms
[main] INFO com.criteo.nosql.mewpoke.couchbase.CouchbaseRunnerAbstract - WAIT took 26652 ms
[main] WARN com.couchbase.client.core.env.CoreEnvironment - More than 1 Couchbase Environments found (2), this can have severe impact on performance and stability. Reuse environments!
[main] INFO com.couchbase.client.core.CouchbaseCore - CouchbaseEnvironment: {sslEnabled=false, sslKeystoreFile='null', sslKeystorePassword=false, sslKeystore=null, bootstrapHttpEnabled=true, bootstrapCarrierEnabled=true, bootstrapHttpDirectPort=8091, bootstrapHttpSslPort=18091, bootstrapCarrierDirectPort=11210, bootstrapCarrierSslPort=11207, ioPoolSize=4, computationPoolSize=4, responseBufferSize=16384, requestBufferSize=16384, kvServiceEndpoints=1, viewServiceEndpoints=12, queryServiceEndpoints=12, searchServiceEndpoints=12, configPollInterval=2500, ioPool=NioEventLoopGroup, kvIoPool=null, viewIoPool=null, searchIoPool=null, queryIoPool=null, coreScheduler=CoreScheduler, memcachedHashingStrategy=DefaultMemcachedHashingStrategy, eventBus=DefaultEventBus, packageNameAndVersion=couchbase-java-client/2.4.7 (git: 2.4.7-1-g01524c6, core: 1.4.7-47-g013dc7a), retryStrategy=BestEffort, maxRequestLifetime=75000, retryDelay=ExponentialDelay{growBy 1.0 MICROSECONDS, powers of 2; lower=100, upper=100000}, reconnectDelay=ExponentialDelay{growBy 1.0 MILLISECONDS, powers of 2; lower=32, upper=4096}, observeIntervalDelay=ExponentialDelay{growBy 1.0 MICROSECONDS, powers of 2; lower=10, upper=100000}, keepAliveInterval=30000, continuousKeepAliveEnabled=true, keepAliveErrorThreshold=4, keepAliveTimeout=2500, autoreleaseAfter=2000, bufferPoolingEnabled=true, tcpNodelayEnabled=true, mutationTokensEnabled=false, socketConnectTimeout=1000, callbacksOnIoPool=false, disconnectTimeout=25000, requestBufferWaitStrategy=com.couchbase.client.core.env.DefaultCoreEnvironment$2@3f56875e, certAuthEnabled=false, coreSendHook=null, queryTimeout=75000, viewTimeout=75000, searchTimeout=75000, analyticsTimeout=75000, kvTimeout=2500, connectTimeout=5000, dnsSrvEnabled=false}
```

**Comment by gfediere** [comment] 2018-03-06 15:24
Hi @blackrez ,

Could you please provide the config file used please ?

**Comment by mcoolive** [comment] 2018-03-09 12:30
Note: the PR [Refactor CouchbaseMonitor](https://github.com/criteo/mewpoke/pull/36) should improve the error message and help to find the root cause of the issue.

**Comment by erebe** [comment] 2018-07-03 12:21
no activity, feel free to re-open if needed

**Closed by erebe** 2018-07-03 12:21 UTC
